"""Build Trippin's built-in dancer library.

    py tools/build_dancer_library.py            # shadow-dancer routines (choreo.py)
    py tools/build_dancer_library.py --modern   # also the CMU modern-dance takes

The default library is choreographed shadow dancing: hip sway, body rolls and
arm shapes, generated by choreo.py on a CMU skeleton. The modern-dance clips
are real mocap from CMU subject 05.

BVH files are cached in tools/.mocap_cache. Edit LIBRARY to add takes; the CMU
index (cmu-mocap-index-text.txt in the repo below) lists everything available.

Motion data credit: "The data used in this project was obtained from
mocap.cs.cmu.edu. The database was created with funding from NSF EIA-0196217."
BVH conversion by B. Hahne (cgspeed.com), mirrored at github.com/una-dinosauria/cmu-mocap.
"""
import subprocess
import sys
import urllib.request
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
CACHE = TOOLS / ".mocap_cache"
BASE = "https://raw.githubusercontent.com/una-dinosauria/cmu-mocap/master/data"

# (CMU take, clip name, camera view)
# Choreographed routines (see ROUTINES in choreo.py), rendered front-on, with
# the energy auto-pilot uses to match them to the track (breakdown .. drop).
SHADOW = {"tease": 0.1, "profile": 0.25, "diva": 0.35, "frame": 0.5,
          "snake": 0.55, "wave": 0.65, "hips": 0.85}

# Real mocap, opt-in with --modern.
LIBRARY = [
    # Modern dance (CMU subject 05), from graceful to explosive.
    ("05_02", "arms_pirouette", "three-quarter"),
    ("05_10", "glissade_arms", "three-quarter"),
    ("05_09", "glissade", "three-quarter"),
    ("05_04", "arabesque_backbend", "three-quarter"),
    ("05_03", "arabesque_turn", "three-quarter"),
    ("05_11", "pirouette_steps", "three-quarter"),
    ("05_13", "jetes_pirouette", "three-quarter"),
    ("05_07", "jete_arabesque", "three-quarter"),
    ("05_08", "rond_de_jambe_leap", "three-quarter"),
    ("05_16", "jete_en_tournant", "three-quarter"),
    ("05_19", "leap_backbend", "three-quarter"),
    # Slow lean with sweeping arms (subject 49), for deep breakdowns.
    ("49_14", "slow_lean", "three-quarter"),
]


def fetch(take):
    CACHE.mkdir(exist_ok=True)
    path = CACHE / f"{take}.bvh"
    if not path.exists():
        subject = take.split("_")[0].zfill(3)
        url = f"{BASE}/{subject}/{take}.bvh"
        print(f"downloading {url}")
        urllib.request.urlretrieve(url, path)
    return path


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--modern", action="store_true", help="also render the CMU modern-dance takes")
    args = ap.parse_args()
    fetch("05_02")  # choreo.py borrows this take's skeleton
    for routine, energy in SHADOW.items():
        print(f"== shadow_{routine}")
        bvh = CACHE / f"choreo_{routine}.bvh"
        subprocess.run([sys.executable, str(TOOLS / "choreo.py"), routine, "--out", str(bvh)], check=True)
        subprocess.run([sys.executable, str(TOOLS / "mocap_dancer.py"), str(bvh), "--name", f"shadow_{routine}",
                        "--view", "front", "--whole", "--beats", "8", "--energy", str(energy)], check=True)
    if args.modern:
        for take, name, view in LIBRARY:
            print(f"== {name} ({take}, {view})")
            subprocess.run([sys.executable, str(TOOLS / "mocap_dancer.py"), str(fetch(take)),
                            "--name", name, "--view", view], check=True)


if __name__ == "__main__":
    main()
