// @heavy — 2026 tier. @bloom 0.85 @tonemap agx
// Front-row seat on a roller coaster through a cyberpunk megacity at night.
// The track is a closed figure-eight circuit (so the ride loops forever,
// like a real coaster): a slow chain-lift up to the summit, then drops,
// banked turns and an over/under crossing, weaving between neon towers.
// Timing is physical — the car crawls over crests and flies through dips —
// and banks into the turns; both are baked by tools/coaster_track.py into
// the Fourier tables below (the shader is stateless: lap position comes
// straight from the tempo clock, so nothing ever stutters).
// Rendering: towers via a 2D grid DDA over city blocks (cells the track
// passes through are cleared), the track drawn ahead as projected neon rails
// with ties and pylons, the car's nose in the foreground.
// Audio: rail lights chase forward on the beat, window blocks and
// billboards follow the spectrum, rails/trim flash with the kick (calm in
// breakdowns). Speed never follows the audio.

const LAP_BEATS: f32 = 96.0;
const S: f32 = 40.0;           // city block size

// ---- GENERATED by tools/coaster_track.py — do not edit by hand ----
const TX: array<vec3<f32>, 2> = array<vec3<f32>, 2>(
    vec3<f32>(1.0, 0.00000, 330.00000),
    vec3<f32>(3.0, 0.00000, 45.00000)
);
const TY: array<vec3<f32>, 4> = array<vec3<f32>, 4>(
    vec3<f32>(1.0, -20.00000, 55.00000),
    vec3<f32>(2.0, 22.00000, 0.00000),
    vec3<f32>(3.0, 0.00000, 14.00000),
    vec3<f32>(5.0, 8.00000, 0.00000)
);
const TZ: array<vec3<f32>, 3> = array<vec3<f32>, 3>(
    vec3<f32>(2.0, 0.00000, 190.00000),
    vec3<f32>(1.0, 60.00000, 0.00000),
    vec3<f32>(3.0, 25.00000, 0.00000)
);
const TY0: f32 = 95.00;
const WARP: array<vec3<f32>, 24> = array<vec3<f32>, 24>(
    vec3<f32>(1.0, 0.28866, 0.55966),
    vec3<f32>(2.0, 0.11565, -0.06910),
    vec3<f32>(3.0, -0.00750, -0.15188),
    vec3<f32>(4.0, -0.02835, -0.06993),
    vec3<f32>(5.0, -0.01355, -0.01964),
    vec3<f32>(6.0, 0.01226, -0.00216),
    vec3<f32>(7.0, 0.00185, 0.00004),
    vec3<f32>(8.0, -0.01209, 0.00598),
    vec3<f32>(9.0, -0.01381, 0.01999),
    vec3<f32>(10.0, 0.00000, 0.02030),
    vec3<f32>(11.0, 0.01333, 0.00638),
    vec3<f32>(12.0, 0.01230, -0.01063),
    vec3<f32>(13.0, 0.00172, -0.01613),
    vec3<f32>(14.0, -0.00642, -0.00894),
    vec3<f32>(15.0, -0.00597, 0.00097),
    vec3<f32>(16.0, -0.00151, 0.00484),
    vec3<f32>(17.0, 0.00051, 0.00350),
    vec3<f32>(18.0, -0.00092, 0.00220),
    vec3<f32>(19.0, -0.00128, 0.00288),
    vec3<f32>(20.0, 0.00143, 0.00296),
    vec3<f32>(21.0, 0.00432, -0.00018),
    vec3<f32>(22.0, 0.00371, -0.00436),
    vec3<f32>(23.0, -0.00030, -0.00543),
    vec3<f32>(24.0, -0.00370, -0.00232)
);
const WARP0: f32 = -0.35907;
const BANK: array<vec3<f32>, 8> = array<vec3<f32>, 8>(
    vec3<f32>(1.0, -0.06884, -0.24405),
    vec3<f32>(2.0, -0.07326, -0.09030),
    vec3<f32>(3.0, 0.04695, -0.15037),
    vec3<f32>(4.0, -0.06289, -0.00165),
    vec3<f32>(5.0, 0.03201, 0.20547),
    vec3<f32>(6.0, 0.09718, 0.04219),
    vec3<f32>(7.0, -0.02412, 0.00083),
    vec3<f32>(8.0, -0.00690, -0.00192)
);
const BANK0: f32 = 0.02306;
const CLEAR_GRID: i32 = 24;
const CLEAR_CELL: f32 = 40.0;
const CLEAR_ROWS: array<u32, 24> = array<u32, 24>(
    0u, 0u, 0u, 0u, 0u, 0u, 1015808u, 1040432u, 847984u, 801008u, 794032u, 790320u, 790320u, 794032u, 801008u, 847984u, 1040432u, 1015808u, 0u, 0u, 0u, 0u, 0u, 0u
);
// ---- END GENERATED ----

// cos/sin of k*th for k = 0..8 by the Chebyshev recurrence (one sincos).
struct Harm {
    c: array<f32, 9>,
    s: array<f32, 9>,
};

fn harm(th: f32) -> Harm {
    var h: Harm;
    let c1 = cos(th);
    let s1 = sin(th);
    h.c[0] = 1.0;
    h.s[0] = 0.0;
    h.c[1] = c1;
    h.s[1] = s1;
    for (var k = 2; k < 9; k++) {
        h.c[k] = h.c[k - 1] * c1 - h.s[k - 1] * s1;
        h.s[k] = h.s[k - 1] * c1 + h.c[k - 1] * s1;
    }
    return h;
}

// Track centreline and its derivative dC/dth.
fn track(h: Harm) -> vec3<f32> {
    var p = vec3<f32>(0.0, TY0, 0.0);
    for (var i = 0; i < 2; i++) {
        let k = i32(TX[i].x);
        p.x += TX[i].y * h.c[k] + TX[i].z * h.s[k];
    }
    for (var i = 0; i < 4; i++) {
        let k = i32(TY[i].x);
        p.y += TY[i].y * h.c[k] + TY[i].z * h.s[k];
    }
    for (var i = 0; i < 3; i++) {
        let k = i32(TZ[i].x);
        p.z += TZ[i].y * h.c[k] + TZ[i].z * h.s[k];
    }
    return p;
}

fn track_d(h: Harm) -> vec3<f32> {
    var d = vec3<f32>(0.0);
    for (var i = 0; i < 2; i++) {
        let k = i32(TX[i].x);
        d.x += TX[i].x * (-TX[i].y * h.s[k] + TX[i].z * h.c[k]);
    }
    for (var i = 0; i < 4; i++) {
        let k = i32(TY[i].x);
        d.y += TY[i].x * (-TY[i].y * h.s[k] + TY[i].z * h.c[k]);
    }
    for (var i = 0; i < 3; i++) {
        let k = i32(TZ[i].x);
        d.z += TZ[i].x * (-TZ[i].y * h.s[k] + TZ[i].z * h.c[k]);
    }
    return d;
}

fn bank(h: Harm) -> f32 {
    var b = BANK0;
    for (var i = 0; i < 8; i++) {
        let k = i32(BANK[i].x);
        b += BANK[i].y * h.c[k] + BANK[i].z * h.s[k];
    }
    return b;
}

// Lap fraction -> track parameter (physical timing), and d(th)/d(phi).
fn warp(phi: f32) -> vec2<f32> {
    var th = TAU * phi + WARP0;
    var dth = TAU;
    for (var i = 0; i < 24; i++) {
        let k = WARP[i].x;
        let a = TAU * k * phi;
        th += WARP[i].y * cos(a) + WARP[i].z * sin(a);
        dth += TAU * k * (-WARP[i].y * sin(a) + WARP[i].z * cos(a));
    }
    return vec2<f32>(th, dth);
}

// Banked frame at a track point: (right, up) with T the unit tangent.
fn frame(t: vec3<f32>, b: f32) -> mat2x3<f32> {
    let r0 = normalize(cross(vec3<f32>(0.0, 1.0, 0.0), t));
    let u0 = cross(t, r0);
    let r = r0 * cos(b) - u0 * sin(b);
    let u = u0 * cos(b) + r0 * sin(b);
    return mat2x3<f32>(r, u);
}

// ---- City -------------------------------------------------------------------

fn cleared(c: vec2<f32>) -> bool {
    let i = i32(c.x) + CLEAR_GRID / 2;
    let j = i32(c.y) + CLEAR_GRID / 2;
    if i < 0 || j < 0 || i >= CLEAR_GRID || j >= CLEAR_GRID {
        return false;
    }
    return ((CLEAR_ROWS[j] >> u32(i)) & 1u) == 1u;
}

// (centre x, centre z, half-size, height); height 0 = no tower.
fn block(c: vec2<f32>) -> vec4<f32> {
    let h = hash22(c * 1.31 + 0.7);
    let ctr = (c + 0.5) * S;
    let half = S * (0.28 + 0.1 * h.y);
    var hgt = 40.0 + pow(h.x, 2.0) * 160.0 + pow(hash21(c + 5.5), 6.0) * 180.0;
    if cleared(c) || hash21(c + 9.1) < 0.06 {
        hgt = 0.0;
    }
    return vec4<f32>(ctr, half, hgt);
}

struct CityHit {
    t: f32,
    n: vec3<f32>,
    cell: vec2<f32>,
    h: f32,
};

fn trace_city(ro: vec3<f32>, rd: vec3<f32>, steps: i32, tmax: f32) -> CityHit {
    var res: CityHit;
    res.t = -1.0;
    var cell = floor(ro.xz / S);
    let stp = sign(rd.xz);
    let inv = 1.0 / max(abs(rd.xz), vec2<f32>(1e-5));
    var tm = ((cell + max(stp, vec2<f32>(0.0))) * S - ro.xz) / rd.xz;
    let td = S * inv;
    for (var i = 0; i < steps; i++) {
        let b = block(cell);
        if b.w > 0.0 {
            let c3 = vec3<f32>(b.x, b.w * 0.5, b.y);
            let h3 = vec3<f32>(b.z, b.w * 0.5, b.z);
            let ib = 1.0 / rd;
            let t0 = (c3 - h3 - ro) * ib;
            let t1 = (c3 + h3 - ro) * ib;
            let tmin = min(t0, t1);
            let tmx = max(t0, t1);
            let tn = max(max(tmin.x, tmin.y), tmin.z);
            let tf = min(min(tmx.x, tmx.y), tmx.z);
            if tn < tf && tn > 0.0 {
                res.t = tn;
                res.cell = cell;
                res.h = b.w;
                if tn == tmin.x {
                    res.n = vec3<f32>(-sign(rd.x), 0.0, 0.0);
                } else if tn == tmin.y {
                    res.n = vec3<f32>(0.0, 1.0, 0.0);
                } else {
                    res.n = vec3<f32>(0.0, 0.0, -sign(rd.z));
                }
                return res;
            }
        }
        if tm.x < tm.y {
            cell.x += stp.x;
            tm.x += td.x;
        } else {
            cell.y += stp.y;
            tm.y += td.y;
        }
        if min(tm.x, tm.y) > tmax {
            break;
        }
    }
    return res;
}

fn sky(rd: vec3<f32>) -> vec3<f32> {
    let h = max(rd.y, 0.0);
    // Smog lit from below by the city: magenta low, deep indigo up high.
    var c = mix(vec3<f32>(0.16, 0.04, 0.12), vec3<f32>(0.01, 0.008, 0.03), smoothstep(0.0, 0.45, h));
    let cl = tnoise(vec3<f32>(rd.xz / max(rd.y + 0.2, 0.05) * 0.04, u.time * 0.002)).r;
    c *= 0.6 + 1.3 * cl;
    return c;
}

fn facade(p: vec3<f32>, n: vec3<f32>, cell: vec2<f32>, hgt: f32) -> vec3<f32> {
    let uu = select(p.x, p.z, abs(n.x) > 0.5);
    // Vertical neon edge strips on tower corners.
    let e = fract(uu / (S * 0.1) + 0.5);
    var c = vec3<f32>(0.01, 0.01, 0.018);
    let g = vec2<f32>(uu * 0.7, p.y * 0.45);
    let wc = floor(g);
    let f = fract(g);
    let pane = smoothstep(0.42, 0.32, abs(f.x - 0.5)) * smoothstep(0.4, 0.28, abs(f.y - 0.5));
    let h = hash21(wc + cell * 7.3 + n.xz * 3.0);
    var lit = step(0.8, h);
    let band = fract(cell.x * 0.13 + cell.y * 0.07);
    let wave = smoothstep(0.7, 1.0, sin(length(cell) * 0.5 - u.flow * 0.5) * 0.5 + 0.5);
    lit = max(lit, step(0.45, h) * wave * spec(band * 0.8) * 1.5 * u.intensity);
    let tone = mix(vec3<f32>(0.3, 0.9, 1.0), vec3<f32>(1.0, 0.3, 0.8), step(0.5, hash21(wc + 3.3)));
    c += tone * lit * pane * 0.7;
    // Horizontal neon bands on some towers.
    if hash21(cell + 2.2) < 0.4 {
        // Thin strips (~0.6 m) every 24 m of height.
        let bandy = smoothstep(0.025, 0.0, abs(fract(p.y / 24.0) - 0.5));
        c += palette(hash21(cell) + u.hue) * bandy * 1.2;
    }
    // Giant LED billboards (spectrum) high on some towers.
    if hash21(cell + 4.4) < 0.3 && abs(n.y) < 0.5 && hgt > 70.0 {
        let top = hgt - 8.0;
        let bw = fract(uu / S + 0.5);
        if p.y > top - 30.0 && p.y < top && abs(bw - 0.5) < 0.4 {
            let x = abs(bw - 0.5) / 0.4;
            let col_id = floor(x * 16.0);
            let lvl = spec(col_id / 16.0 * 0.8);
            let yy = (p.y - (top - 30.0)) / 30.0;
            let bar = step(yy, lvl * 0.95) * smoothstep(0.45, 0.3, abs(fract(x * 16.0) - 0.5));
            let pal = palette(col_id / 16.0 * 0.7 + hash21(cell) * 0.5 + u.hue);
            c = pal * (0.06 + bar * 2.0) * (0.6 + 0.8 * u.intensity);
        }
    }
    return c;
}

fn shade_city(ro: vec3<f32>, rd: vec3<f32>, h: CityHit) -> vec3<f32> {
    let hp = ro + rd * h.t;
    var c = facade(hp, h.n, h.cell, h.h);
    if h.n.y > 0.5 {
        c = vec3<f32>(0.012, 0.01, 0.02) + vec3<f32>(1.0, 0.1, 0.1) * step(0.85, hash21(h.cell + 2.0)) * smoothstep(1.5, 0.0, length(hp.xz - block(h.cell).xy)) * (0.5 + 0.5 * sin(u.time * 3.0 + h.cell.x));
    }
    return c;
}

// ---- Screen-space line helper ------------------------------------------------

fn seg2(p: vec2<f32>, a: vec2<f32>, b: vec2<f32>) -> vec2<f32> {
    let pa = p - a;
    let ba = b - a;
    let t = clamp(dot(pa, ba) / max(dot(ba, ba), 1e-9), 0.0, 1.0);
    return vec2<f32>(length(pa - ba * t), t);
}

@fragment
fn fs_main(in: VsOut) -> @location(0) vec4<f32> {
    let p = centred(in.uv);
    let drive = 0.5 + 0.8 * u.intensity;

    // --- Where the car is ------------------------------------------------------
    let phi = fract(u.flow / LAP_BEATS + u.seed * 0.0137);
    let w = warp(phi);
    let hc = harm(w.x);
    let cpos = track(hc);
    let cd = track_d(hc);
    let T = normalize(cd);
    let fr = frame(T, bank(hc));
    let speed = length(cd) * w.y;            // metres per lap-fraction
    let spd_n = clamp((speed / LAP_BEATS / 0.5 - 20.0) / 50.0, 0.0, 1.0);
    let ro = cpos + fr[1] * 1.5;
    // Look a touch ahead along the track (smooths the view in turns).
    let ha = harm(w.x + 0.025);
    let ahead = normalize(track(ha) + frame(normalize(track_d(ha)), bank(ha))[1] * 1.5 - ro);
    let fwd = normalize(mix(T, ahead, 0.7));
    let rgt = normalize(fr[0] - fwd * dot(fr[0], fwd));
    let upv = cross(fwd, rgt);
    // Wider FOV at speed.
    let fl = 1.15 - 0.3 * spd_n;
    let rd = normalize(rgt * p.x - upv * p.y + fwd * fl);

    // --- Background: city, ground, sky ---------------------------------------------
    var col = sky(rd);
    var t_hit = 3000.0;
    let ch = trace_city(ro, rd, 56, 2000.0);
    let t_ground = select(1e5, -ro.y / rd.y, rd.y < 0.0);
    if ch.t > 0.0 && ch.t < t_ground {
        t_hit = ch.t;
        col = shade_city(ro, rd, ch);
    } else if t_ground < 1e4 {
        t_hit = t_ground;
        let gp = ro + rd * t_ground;
        // Wet street: neon lane lines + a short reflection trace.
        let rr = vec3<f32>(rd.x, -rd.y, rd.z);
        let rh = trace_city(gp + rr * 0.1, rr, 14, 400.0);
        var refl = sky(rr) * 0.5;
        if rh.t > 0.0 {
            refl = shade_city(gp, rr, rh);
        }
        let lane = smoothstep(0.4, 0.0, abs(fract(gp.x / S) - 0.5) - 0.46) + smoothstep(0.4, 0.0, abs(fract(gp.z / S) - 0.5) - 0.46);
        col = vec3<f32>(0.01, 0.008, 0.016) + refl * fresnel(0.1, -rd.y) * 0.9 + palette(0.6 + u.hue) * lane * 0.06;
    }
    // Smog: magenta haze with distance, thicker low down.
    let fog = 1.0 - exp(-t_hit * 0.0018);
    let hfog = exp(-max(ro.y + rd.y * min(t_hit, 800.0) * 0.5, 0.0) * 0.012);
    col = mix(col, vec3<f32>(0.12, 0.035, 0.1) * drive, clamp(fog * (0.6 + 0.6 * hfog), 0.0, 1.0));

    // --- The track ahead: rails, ties, pylons -----------------------------------------
    var rails = vec3<f32>(0.0);
    let base_step = 5.0 / max(length(cd), 1.0);        // ~5 m per sample near the car
    var th_i = w.x + base_step * 0.4;
    var prev_l = vec3<f32>(0.0);
    var prev_r = vec3<f32>(0.0);
    var prev_ok = false;
    let px = 2.0 / u.res_y;
    var deck = 0.0;
    for (var i = 0; i < 40; i++) {
        let hi = harm(th_i);
        let tp = track(hi);
        let tt = normalize(track_d(hi));
        let tf = frame(tt, bank(hi));
        let rl = tp - tf[0] * 0.75 + tf[1] * 0.1;
        let rr2 = tp + tf[0] * 0.75 + tf[1] * 0.1;
        // Project (camera basis).
        let vl = rl - ro;
        let vr = rr2 - ro;
        let zl = dot(vl, fwd);
        let zr = dot(vr, fwd);
        let ok = zl > 0.4 && zr > 0.4;
        let sl = vec2<f32>(dot(vl, rgt), -dot(vl, upv)) / zl * fl;
        let sr = vec2<f32>(dot(vr, rgt), -dot(vr, upv)) / zr * fl;
        let dist = length(vl);
        let vis = step(dist, t_hit + 2.0);
        // Chase lights running forward along the rails with the beat.
        let chase = pow(0.5 + 0.5 * cos(th_i * 260.0 - u.flow * TAU), 8.0);
        let rail_c = mix(palette(0.55 + u.hue), vec3<f32>(1.0, 0.3, 0.9), 0.4);
        let lvl = (0.5 + 1.8 * chase * (0.4 + spec(0.1))) * (0.6 + 0.9 * beat_pulse(6.0)) * drive;
        let fade = exp(-dist * 0.004);
        if ok && prev_ok {
            // Deck: the dark track structure between the rails (a screen
            // quad per segment) — hides what's behind it, so it reads solid.
            let a = prev_l.xy;
            let b = prev_r.xy;
            let c2 = sr;
            let d2 = sl;
            let e0 = (b.x - a.x) * (p.y - a.y) - (b.y - a.y) * (p.x - a.x);
            let e1 = (c2.x - b.x) * (p.y - b.y) - (c2.y - b.y) * (p.x - b.x);
            let e2 = (d2.x - c2.x) * (p.y - c2.y) - (d2.y - c2.y) * (p.x - c2.x);
            let e3 = (a.x - d2.x) * (p.y - d2.y) - (a.y - d2.y) * (p.x - d2.x);
            let inside = (e0 >= 0.0 && e1 >= 0.0 && e2 >= 0.0 && e3 >= 0.0) || (e0 <= 0.0 && e1 <= 0.0 && e2 <= 0.0 && e3 <= 0.0);
            if inside && deck < 0.5 && dist < t_hit + 2.0 {
                deck = 1.0;
                col = vec3<f32>(0.012, 0.012, 0.02) + palette(0.55 + u.hue) * 0.02 * fade;
            }
            let w_rail = max(0.12 / zl * fl, px * 1.2);
            let dl = seg2(p, prev_l.xy, sl).x;
            let dr = seg2(p, prev_r.xy, sr).x;
            let d = min(dl, dr);
            let line = smoothstep(w_rail, 0.0, d) * 1.5 + exp(-d / (w_rail * 4.0)) * 0.35;
            rails += rail_c * line * lvl * vis * fade;
        }
        if ok {
            // Tie across the rails.
            if (i & 1) == 0 {
                let dt = seg2(p, sl, sr).x;
                let w_tie = max(0.05 / zl * fl, px * 0.6);
                rails += vec3<f32>(0.25, 0.3, 0.4) * smoothstep(w_tie, 0.0, dt) * 0.4 * vis * fade * drive;
            }
            // Pylon down to the street every few samples.
            // (Hidden where a nearer bit of deck already covers the pixel.)
            if i % 6 == 3 && deck < 0.5 {
                let gpt = vec3<f32>(tp.x, 0.0, tp.z) - ro;
                let zg = dot(gpt, fwd);
                if zg > 0.4 {
                    let sg = vec2<f32>(dot(gpt, rgt), -dot(gpt, upv)) / zg * fl;
                    let smid = (sl + sr) * 0.5;
                    let dp = seg2(p, smid, sg);
                    let w_p = max(0.35 / zl * fl, px);
                    let body = smoothstep(w_p, w_p * 0.6, dp.x);
                    // Dark column occludes what's behind it, with a neon edge.
                    let vis_p = step(length(tp - ro), t_hit + 2.0);
                    col = mix(col, vec3<f32>(0.01, 0.01, 0.015), body * vis_p);
                    rails += palette(0.1 + u.hue) * smoothstep(w_p * 0.3, 0.0, abs(dp.x - w_p * 0.8)) * 0.35 * vis_p * fade * drive;
                }
            }
        }
        prev_l = vec3<f32>(sl, zl);
        prev_r = vec3<f32>(sr, zr);
        prev_ok = ok;
        // Step grows with distance (dense near, sparse far).
        th_i += base_step * (1.0 + f32(i) * 0.15);
    }
    col += rails;

    // --- The car's nose -----------------------------------------------------------
    // A dark rounded nose low in frame, with neon trim that pulses on the kick.
    let nose_y = 0.72 + 0.06 * p.x * p.x;
    let nose = smoothstep(nose_y, nose_y + 0.01, p.y);
    let trim = exp(-abs(p.y - nose_y) * 180.0) * smoothstep(1.3, 0.3, abs(p.x));
    let lap_bar = smoothstep(0.012, 0.0, abs(p.y - (0.9 + 0.02 * p.x * p.x))) * step(abs(p.x), 0.9);
    col = mix(col, vec3<f32>(0.006, 0.006, 0.01) + col * 0.05, nose);
    col += vec3<f32>(0.2, 0.9, 1.0) * trim * (0.6 + 1.6 * beat_pulse(6.0)) * drive;
    col += vec3<f32>(0.8, 0.2, 0.7) * lap_bar * 0.35 * nose;

    // Speed streaks at the frame edges when flying.
    let edge = smoothstep(0.6, 1.4, length(p));
    let streak = hash21(vec2<f32>(floor(angle(p) * 60.0), floor(u.flow * 8.0)));
    col += vec3<f32>(0.5, 0.7, 1.0) * edge * step(0.985, streak) * spd_n * 0.05;

    col += (bluen(in.pos.xy) - 0.5) * 0.003;
    return vec4<f32>(col, 1.0);
}
